import { useState, useEffect } from 'react';
import { Html5QrcodeScanner } from 'html5-qrcode';
import { academicAPI } from '../services/api';
import MainLayout from '../components/layout/MainLayout';
import CopilotChat from './CopilotChat';
import LivenessCheck from '../components/LivenessCheck';
import Card from '../components/ui/Card';
import Button from '../components/ui/Button';
import Badge from '../components/ui/Badge';
import Input from '../components/ui/Input';
import './Dashboard.css';

function StudentDashboard({ user, handleLogout }) {
    const [activeTab, setActiveTab] = useState('copilot'); // 'copilot' or 'attendance'
    const [attendanceHistory, setAttendanceHistory] = useState([]);
    const [showScanner, setShowScanner] = useState(false);
    const [scanResult, setScanResult] = useState(null);
    const [manualCode, setManualCode] = useState('');
    const [loading, setLoading] = useState(true);

    // Liveness flow state
    const [pendingQrPayload, setPendingQrPayload] = useState(null);
    const [showLiveness, setShowLiveness] = useState(false);

    useEffect(() => { 
        if (activeTab === 'attendance') {
            fetchAttendance(); 
        } else {
            setLoading(false);
        }
    }, [activeTab]);

    useEffect(() => {
        if (showScanner) {
            const scanner = new Html5QrcodeScanner(
                "reader", { fps: 10, qrbox: { width: 250, height: 250 } }, false
            );
            scanner.render(onScanSuccess, () => {});
            return () => { scanner.clear().catch(() => {}); };
        }
    }, [showScanner]);

    const fetchAttendance = async () => {
        setLoading(true);
        try {
            const res = await academicAPI.getStudentAttendance();
            setAttendanceHistory(res.data || []);
        } catch (error) {
            console.error("Failed to fetch attendance", error);
        } finally {
            setLoading(false);
        }
    };

    const onScanSuccess = async (decodedText) => {
        setShowScanner(false);
        try { 
            const payload = JSON.parse(decodedText);
            setPendingQrPayload(payload);
            setScanResult(null);
            setShowLiveness(true); // Trigger liveness check
        } catch { 
            setScanResult({ error: "Invalid QR code format. Not generated by Copilot?" }); 
        }
    };

    const handleLivenessVerified = (base64Image) => {
        setShowLiveness(false);
        processAttendance(pendingQrPayload.sessionId, pendingQrPayload.courseCode, base64Image, true);
    };

    const handleLivenessCancel = () => {
        setShowLiveness(false);
        setPendingQrPayload(null);
        setScanResult({ error: "Liveness check cancelled. Attendance not marked." });
    };

    const handleManualSubmit = () => {
        if (!manualCode || manualCode.length !== 6) {
            setScanResult({ error: "Please enter a valid 6-digit code." });
            return;
        }
        processAttendance(null, null, null, false, manualCode);
    };

    const processAttendance = (sessionId, courseCode, faceImageBase64, isLivenessVerified, sessionCode = null) => {
        if (!navigator.geolocation) { 
            setScanResult({ error: "Geolocation is not supported by your browser." }); 
            return; 
        }

        navigator.geolocation.getCurrentPosition(async (position) => {
            try {
                const reqData = {
                    latitude: position.coords.latitude,
                    longitude: position.coords.longitude,
                    faceImageBase64,
                    livenessVerified: isLivenessVerified
                };
                
                if (sessionCode) reqData.sessionCode = sessionCode;
                else {
                    reqData.sessionId = sessionId;
                    reqData.courseCode = courseCode;
                }

                const response = await academicAPI.markAttendance(reqData);
                setScanResult({ success: "Identity verified & Attendance marked successfully!", data: response.data });
                setPendingQrPayload(null);
                setManualCode('');
                fetchAttendance();
            } catch (error) {
                setScanResult({ error: error.response?.data?.error || "Failed to mark attendance" });
                setPendingQrPayload(null);
            }
        }, () => { 
            setScanResult({ error: "Location access is strictly required to mark attendance." }); 
            setPendingQrPayload(null);
        });
    };

    const totalClasses = attendanceHistory.length;
    const presentClasses = attendanceHistory.filter(r => r.status === 'PRESENT').length;
    const attendancePercentage = totalClasses > 0 ? Math.round((presentClasses / totalClasses) * 100) : 0;

    return (
        <MainLayout user={user} handleLogout={handleLogout} activeTab={activeTab} setActiveTab={setActiveTab}>
            {activeTab === 'copilot' ? (
                <div className="fade-in"><CopilotChat /></div>
            ) : (
                <div className="fade-in">
                    <div className="page-header" style={{ marginBottom: '2rem' }}>
                        <h1>Smart Attendance</h1>
                        <p>Liveness-verified, geofenced class attendance.</p>
                    </div>

                    <div className="stats-overview" style={{ gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))' }}>
                        <Card noPadding={false}>
                            <div className="stat-header">
                                <span className="stat-desc" style={{ marginTop: 0 }}>Attendance</span>
                            </div>
                            <p className="stat-value">{attendancePercentage}%</p>
                            <Badge variant={attendancePercentage >= 75 ? 'success' : 'error'}>
                                {attendancePercentage >= 75 ? 'Good Standing' : 'Needs Improvement'}
                            </Badge>
                        </Card>
                        <Card noPadding={false}>
                            <div className="stat-header">
                                <span className="stat-desc" style={{ marginTop: 0 }}>Total Classes</span>
                            </div>
                            <p className="stat-value">{totalClasses}</p>
                            <span style={{ color: 'var(--text-secondary)' }}>{presentClasses} Present</span>
                        </Card>
                    </div>

                    <div className="dashboard-grid">
                        <div className="dashboard-column">
                            <Card title="Mark Attendance">
                                <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem', fontSize: '0.9rem' }}>
                                    Scanning a QR code will activate your camera for a quick liveness check (blink twice).
                                </p>
                                <Button variant="primary" onClick={() => { setShowScanner(!showScanner); setScanResult(null); }}>
                                    {showScanner ? "Close Scanner" : "Scan QR Code"}
                                </Button>

                                {showScanner && (
                                    <div style={{ marginTop: '1.5rem', border: '1px solid var(--border-default)', borderRadius: 'var(--radius-md)', overflow: 'hidden' }}>
                                        <div id="reader"></div>
                                    </div>
                                )}

                                <div style={{ marginTop: '2rem', paddingTop: '1.5rem', borderTop: '1px solid var(--border-default)' }}>
                                    <h4 style={{ margin: '0 0 1rem 0', fontSize: '0.9rem' }}>Manual Entry (Fallback)</h4>
                                    <div style={{ display: 'flex', gap: '0.5rem' }}>
                                        <Input 
                                            placeholder="6-DIGIT CODE" 
                                            maxLength="6" 
                                            value={manualCode}
                                            onChange={(e) => setManualCode(e.target.value.toUpperCase())} 
                                            style={{ letterSpacing: '0.1em', fontWeight: 'bold', flex: 1 }} 
                                        />
                                        <Button variant="secondary" onClick={handleManualSubmit}>Submit</Button>
                                    </div>
                                </div>

                                {scanResult && (
                                    <div style={{ marginTop: '1.5rem' }}>
                                        <Card style={{ background: scanResult.success ? 'var(--success-bg)' : 'var(--error-bg)', borderColor: 'transparent', color: scanResult.success ? 'var(--success-text)' : 'var(--error-text)' }}>
                                            <strong>{scanResult.success ? "Success: " : "Error: "}</strong> {scanResult.success || scanResult.error}
                                        </Card>
                                    </div>
                                )}
                            </Card>
                        </div>
                        <div className="dashboard-column">
                            <Card title="Recent Records">
                                <ul className="history-list">
                                    {attendanceHistory.slice(0, 10).map((record) => (
                                        <li key={record.id} className="history-item" style={{ display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid var(--border-subtle)', padding: '0.75rem 0' }}>
                                            <div>
                                                <div style={{ fontWeight: 600 }}>{record.courseCode}</div>
                                                <div style={{ fontSize: '0.75rem', color: 'var(--text-tertiary)' }}>
                                                    {new Date(record.markedAt).toLocaleString()} • {record.verificationType}
                                                </div>
                                            </div>
                                            <Badge variant={record.status === 'PRESENT' ? 'success' : 'error'}>{record.status}</Badge>
                                        </li>
                                    ))}
                                    {attendanceHistory.length === 0 && !loading && <p className="empty-state">No records found.</p>}
                                    {loading && <p className="empty-state">Loading...</p>}
                                </ul>
                            </Card>
                        </div>
                    </div>
                </div>
            )}

            {showLiveness && (
                <LivenessCheck 
                    onVerified={handleLivenessVerified} 
                    onCancel={handleLivenessCancel} 
                />
            )}
        </MainLayout>
    );
}

export default StudentDashboard;
